#!/usr/bin/php

<?php

/*
Dump all passwords from www.mysql-password.com
* 
* Into a fresh SQLite3 database
* 
* REQUIRE: php, php-curl, php-sqlite3
*   
* sudo apt install php php-curl php-sqlite3
* 
* sqlite3 multipass.db
* 

CREATE TABLE Users ( 
  SerialNo INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  pass TEXT NOT NULL UNIQUE,
  LEN TEXT NOT NULL );

  * Run me: 
  * 
  * chmod +X passCrap
  * ./passCrap
  * 
  * Or: 
  * 
  * php <(curl -s https://raw.githubusercontent.com/webdev23/passCrap/master/passCrap)
  * 
  * nk @ https://github.com/webdev23/passCrap
  * ponyhacks.com 2017
*/  
error_reporting(0);

   class scrapDB extends SQLite3
   {
      function __construct()
      {
         $this->open('multipass.db');
      }
   }
   
   $db = new scrapDB();
   
   if(!$db){
      echo $db->lastErrorMsg();
   } else {
      echo "Success: multipass.db created!\n";
   };
   
$sql =<<<EOF
CREATE TABLE Users ( 
  SerialNo INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  pass TEXT NOT NULL UNIQUE,
  LEN TEXT NOT NULL );
EOF;

   $ret = $db->exec($sql);
   if(!$ret){
      echo $db->lastErrorMsg();
   } else {
      echo "\nTable insertion done.\n";
   }  
 
//~ Start page number
$baseN = 1;
$base = "http://www.mysql-password.com/database/".$baseN++;

echo "\n\033[31m Warning: This tool is going to construct a database \n of 2.420.000.000 passwords from www.mysql-password.com/database.
This database will weight 230 Gigabytes! 
It can takes weeks and will burn a lot.\n \033[0m
Continue? [Y/n] ";

 usleep(3000000);
 
$stdin = fopen('php://stdin', 'r');
$response = rtrim(fgets(STDIN));
 if ($response == 'y' || 'Y') {
     
     for ($page=1;$page<=242240;++$page){
     
        $curl = curl_init();
        curl_setopt_array($curl, Array(
          CURLOPT_URL            => $base++,
          CURLOPT_USERAGENT      => 'passcrapDB',
          CURLOPT_TIMEOUT        => 20,
          CURLOPT_CONNECTTIMEOUT => 20,
          CURLOPT_RETURNTRANSFER => TRUE,
          CURLOPT_ENCODING       => 'UTF-8'
        ));
        $data = curl_exec($curl);
        curl_close($curl);
        
        $dom=new DOMDocument;
        $dom->loadHTML($data);
        $ee=$dom->getElementsByTagName('td');
        
        $pageCount = 0;
        
        for ($p=0;$p<=30000;++$p){
            
            // Max pass chars: 20
             if(preg_match('/\S{20,}/',$ee->item($p)->nodeValue)) { }
             // Min pass chars: 7
               elseif (strlen($ee->item($p)->nodeValue) > 7) {
                  //~ print_r(" ".$ee->item($p)->nodeValue." ");
                $dbl = new scrapDB(); 
                $pass = $ee->item($p)->nodeValue;
                $passLength = strlen($ee->item($p)->nodeValue);
                
                $sql ="
                INSERT INTO Users ( pass, LEN)
                VALUES ( '".$ee->item($p)->nodeValue."', '".$passLength."' );
                ";
                echo "\n";
                $ret;
                    $ret = @$dbl->exec($sql);
                    if(!$ret){
                        echo "\033[37m Skipped: entry exist or chars mismatch \033[0m";
                    } else {
                       echo "\033[36m [#".$page."/242240][Added entry \033[0m\033[38m".$pass."\033[0m\033[36m into db]";
                    }
                    $dbl->close();
            }
        };
       echo "### Seeking ###";
       usleep(3000000);
    };
};    
